FROM tensorflow/serving

# Copy the exported model to the container
COPY ./exported_models/ssd_mobnet_7_class/saved_model /models/ssd_mobnet_7_class/1

# Specify the model base path and the model name
ENV MODEL_BASE_PATH=/models
ENV MODEL_NAME=ssd_mobnet_7_class

# expose the default grcp port
EXPOSE 8500

# Expose the default rest api port
EXPOSE 8501

# Start TensorFlow Serving
CMD tensorflow_model_server --port=8500 --rest_api_port=8501 --model_base_path=${MODEL_BASE_PATH}/${MODEL_NAME} --model_name=${MODEL_NAME}
